### ISSUE TITLE
Option for custom text color

### ISSUE THREAD

**Issue by andrewhuntsmith** [andrewhuntsmith/LiveSplit.PacePlacement#3]
Currently the text can only be white. Allow color selectors for main text and placement text. Maybe option to change color depending on how the run is doing? For example, gold text if in 1st, green if moved up from last segment, red if moved down from last segment.

**Comment by MuteD6** [comment]
That would be sick

**Comment by andrewhuntsmith** [comment]
Added as of commit be2f158
